# Generated by Django 5.1.7 on 2025-04-12 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.CharField(blank=True, max_length=20, null=True)),
                ('edition_format', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_library_collection', models.CharField(blank=True, max_length=500, null=True)),
                ('us_state_or_non_us_nation', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WIS', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('DE', 'Germany'), ('UK', 'United Kingdom'), ('WI', 'West Indies')], max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('viaf', models.CharField(blank=True, max_length=256, null=True)),
                ('start_century', models.CharField(blank=True, choices=[('18', '18th-Cenutry'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('end_century', models.CharField(blank=True, choices=[('18', '18th-Cenutry'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('X', 'N/A')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Provenance Name',
                'verbose_name_plural': 'Provenance Names',
            },
        ),
        migrations.CreateModel(
            name='StaticPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('viewname', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Static Pages',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='titleicon')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=20)),
                ('start_date', models.IntegerField(default=0)),
                ('end_date', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheatleycensus.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_number', models.CharField(max_length=50, unique=True)),
                ('verification', models.CharField(blank=True, choices=[('U', 'Unverified'), ('V', 'Verified'), ('F', 'False')], max_length=1, null=True)),
                ('shelfmark', models.CharField(blank=True, max_length=500, null=True)),
                ('catalogue_url', models.URLField(blank=True, max_length=500, null=True)),
                ('fragment', models.BooleanField(default=False)),
                ('from_estc', models.BooleanField(default=False)),
                ('digital_facsimile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('binding', models.CharField(blank=True, max_length=500, null=True)),
                ('marginalia', models.TextField(blank=True, null=True)),
                ('prov_info', models.TextField(blank=True, null=True)),
                ('bibliography', models.TextField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('backend_notes', models.TextField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=500, null=True)),
                ('examined_by', models.CharField(blank=True, max_length=500, null=True)),
                ('collated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheatleycensus.issue')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wheatleycensus.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_records', to='wheatleycensus.copy')),
                ('provenance_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheatleycensus.provenancename')),
            ],
        ),
        migrations.AddField(
            model_name='copy',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_records', to='wheatleycensus.provenancerecord'),
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheatleycensus.title'),
        ),
    ]
