# Generated by Django 5.1.7 on 2025-04-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheatleycensus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='marc_code',
            field=models.IntegerField(blank=True, help_text='(optional) MARC code for this location', null=True),
        ),
    ]
