# Generated by Django 5.1.7 on 2025-04-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheatleycensus', '0002_location_marc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='collated_by',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='examined_by',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='verified_by',
        ),
        migrations.AlterField(
            model_name='location',
            name='marc_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='MARC Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='us_state_or_non_us_nation',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('DC', 'District of Columbia'), ('DE', 'Germany'), ('UK', 'United Kingdom'), ('WI', 'West Indies')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='provenancename',
            name='end_century',
            field=models.CharField(blank=True, choices=[('18', '18th‑Century'), ('19', '19th‑Century'), ('20', 'Post‑1900')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='provenancename',
            name='start_century',
            field=models.CharField(blank=True, choices=[('18', '18th‑Century'), ('19', '19th‑Century'), ('20', 'Post‑1900')], max_length=2, null=True),
        ),
    ]
