# Generated by Django 4.2 on 2023-11-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('guardian', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cen', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('verification', models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('E', 'Examined'), ('F', 'False')], default='Unverified', max_length=1)),
                ('Shelfmark', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Digital_Facsimile_URL', models.URLField(blank=True, max_length=500, null=True)),
                ('Height', models.FloatField(blank=True, default=0, null=True)),
                ('Width', models.FloatField(blank=True, default=0, null=True)),
                ('Binding', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('in_early_sammelband', models.BooleanField(default=False)),
                ('Marginalia', models.TextField(blank=True, default='', null=True)),
                ('Local_Notes', models.TextField(blank=True, default='', null=True)),
                ('prov_info', models.TextField(blank=True, default='', null=True)),
                ('bibliography', models.TextField(blank=True, default='', null=True)),
                ('from_estc', models.BooleanField(default=False)),
                ('catalogue_history', models.TextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_submitted_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Copies',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edition_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Edition_format', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('viaf', models.CharField(blank=True, max_length=256, null=True)),
                ('start_century', models.CharField(blank=True, choices=[('17', 'Pre-1700'), ('18', '18th-Cenutry'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('end_century', models.CharField(blank=True, choices=[('17', 'Pre-1700'), ('18', '18th-Cenutry'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('X', 'N/A')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('viewname', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Static Pages',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('apocryphal', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='titleicon')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlowecensus.copy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlowecensus.provenancename')),
            ],
            options={
                'verbose_name_plural': 'Provenance Ownership Records',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STC_Wing', models.CharField(max_length=20)),
                ('ESTC', models.CharField(max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('start_date', models.IntegerField(default=0)),
                ('end_date', models.IntegerField(default=0)),
                ('DEEP', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('Variant_Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlowecensus.edition')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlowecensus.title'),
        ),
        migrations.AddField(
            model_name='copy',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlowecensus.issue'),
        ),
        migrations.AddField(
            model_name='copy',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marlowecensus.location'),
        ),
        migrations.AddField(
            model_name='copy',
            name='provenance_search_names',
            field=models.ManyToManyField(through='marlowecensus.ProvenanceOwnership', to='marlowecensus.provenancename'),
        ),
    ]
