# Generated by Django 4.2 on 2024-02-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marlowecensus', '0003_alter_provenanceownership_options_copy_examined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provenancename',
            options={'verbose_name': 'Provenance Name', 'verbose_name_plural': 'Provenance Names'},
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='catalogue_history',
            new_name='backend_notes',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='examined',
            new_name='fragment',
        ),
        migrations.AddField(
            model_name='copy',
            name='collated_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='copy',
            name='examined_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='copy',
            name='verified_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_submitted_copies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='Variant_Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
