# Generated by Django 4.2 on 2024-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0004_alter_provenancename_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='collated_by',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='examined_by',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
