# Generated by Django 4.2 on 2024-03-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0006_rename_cen_copy_mc_title_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='MC',
            new_name='census_id',
        ),
    ]
