# Generated by Django 4.2 on 2024-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0007_rename_mc_copy_census_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='census_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='MC#'),
        ),
    ]
