# Generated by Django 4.2 on 2024-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0008_alter_copy_census_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='Variant_Description',
        ),
        migrations.AddField(
            model_name='edition',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
