# Generated by Django 4.2 on 2024-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0009_remove_issue_variant_description_edition_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='Sammelband',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
