# Generated by Django 4.2 on 2024-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0010_copy_sammelband'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='Edition_format',
            new_name='edition_format',
        ),
        migrations.RenameField(
            model_name='edition',
            old_name='Edition_number',
            new_name='edition_number',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='DEEP',
            new_name='deep',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='ESTC',
            new_name='estc',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='STC_Wing',
            new_name='stc_wing',
        ),
    ]
