# Generated by Django 4.2 on 2024-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0011_rename_edition_format_edition_edition_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='Binding',
            new_name='binding',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Local_Notes',
            new_name='local_notes',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Marginalia',
            new_name='marginalia',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Sammelband',
            new_name='sammelband',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Shelfmark',
            new_name='shelfmark',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Width',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='copy',
            name='prov_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Provenance'),
        ),
    ]
