# Generated by Django 4.2 on 2024-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlowecensus', '0012_rename_binding_copy_binding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='digital_facsimile_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Digital Facsimile URL'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='from_estc',
            field=models.BooleanField(default=False, verbose_name='From ESTC'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='prov_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Provenance notes'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='verification',
            field=models.CharField(blank=True, choices=[('U', 'Unverified'), ('V', 'Verified'), ('F', 'False')], max_length=1, null=True),
        ),
    ]
